modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/CrabCraftMC/CrabCraft/issues"

[[mods]]
modId = "crabutilities"
version = "${version}"
displayName = "CrabUtilities"
authors = "Max"
description = '''
Pushes Minecraft player stats and advancements to the CrabCraft Velocity proxy via Redis Pub/Sub so they show up on the public Web API and leaderboards.
'''

[[dependencies.crabutilities]]
    modId = "forge"
    mandatory = true
    versionRange = "[47,)"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.crabutilities]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "NONE"
    side = "SERVER"
