services:
  crabcraft-web:
    container_name: crabcraft-web
    image: ghcr.io/crabcraftmc/crabcraft/web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
      - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
      - INFISICAL_ENV=${INFISICAL_ENV:-prod}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
