server-ip=127.0.0.1
server-port=25565
online-mode=true
gamemode=survival
force-gamemode=false
difficulty=normal
op-permission-level=4
spawn-protection=0
max-players=2
white-list=false
motd=CrabCraft Halloween Test
level-type=minecraft:flat
view-distance=6
simulation-distance=6
generator-settings={"layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":2},{"block":"minecraft:grass_block","height":1}],"biome":"minecraft:plains"}
