server-ip=127.0.0.1
server-port=25565
online-mode=true
gamemode=creative
force-gamemode=true
difficulty=normal
op-permission-level=4
spawn-protection=0
enable-command-block=true
max-players=2
white-list=false
motd=CrabCraft Bingo Week 5 Test
