// AUTO-GENERATED from MinecraftStats (https://github.com/pdinklag/MinecraftStats) EN localization + stat definitions.
// Source: stats/*.json + www/localization/en.json
// Do not edit by hand; regenerate by copying assets from upstream.

export type AwardUnit = "int" | "ticks" | "cm" | "tenths_of_heart";
export type AwardBucket = "combat" | "mining" | "crafting" | "building" | "items" | "food" | "movement" | "misc";

export interface AwardMeta {
  id: string;
  title: string;
  desc: string;
  unit: AwardUnit;
  bucket: AwardBucket;
  icon: string;
}

export const AWARDS: Record<string, AwardMeta> = {
  aviate: { id: "aviate", title: "Aviator", desc: "Distance gone by elytra", unit: "cm", bucket: "movement", icon: "/awards/icons/aviate.png" },
  biomes: { id: "biomes", title: "Explorer", desc: "Biomes discovered", unit: "int", bucket: "misc", icon: "/awards/icons/biomes.png" },
  break_tools: { id: "break_tools", title: "Oh Snap", desc: "Tools broken", unit: "int", bucket: "items", icon: "/awards/icons/break_tools.png" },
  breed: { id: "breed", title: "Ranch", desc: "Animals bred", unit: "int", bucket: "misc", icon: "/awards/icons/breed.png" },
  climb: { id: "climb", title: "Climber", desc: "Distance climbed", unit: "cm", bucket: "movement", icon: "/awards/icons/climb.png" },
  collect_berries: { id: "collect_berries", title: "Berry Collector", desc: "Berries collected", unit: "int", bucket: "food", icon: "/awards/icons/collect_berries.png" },
  collect_shroom: { id: "collect_shroom", title: "Fun Guy", desc: "Mushrooms collected", unit: "int", bucket: "food", icon: "/awards/icons/collect_shroom.png" },
  craft_armor: { id: "craft_armor", title: "Armorer", desc: "Pieces of armor crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_armor.png" },
  craft_beacon: { id: "craft_beacon", title: "Power Source", desc: "Beacons crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_beacon.png" },
  craft_bookshelf: { id: "craft_bookshelf", title: "Librarian", desc: "Bookshelves crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_bookshelf.png" },
  craft_bread: { id: "craft_bread", title: "Baker", desc: "Breads, cakes and cookies made", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_bread.png" },
  craft_bundle: { id: "craft_bundle", title: "Backpacker", desc: "Bundles crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_bundle.png" },
  craft_clock: { id: "craft_clock", title: "Timekeeper", desc: "Clocks crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_clock.png" },
  craft_compass: { id: "craft_compass", title: "Navigator", desc: "Compasses crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_compass.png" },
  craft_ender_chest: { id: "craft_ender_chest", title: "Grief This!", desc: "Ender chests crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_ender_chest.png" },
  craft_glowstone: { id: "craft_glowstone", title: "Illuminator", desc: "Glowstone crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_glowstone.png" },
  craft_mineral_block: { id: "craft_mineral_block", title: "Compressor", desc: "Mineral blocks crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_mineral_block.png" },
  craft_paper: { id: "craft_paper", title: "Paperboy", desc: "Paper produced", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_paper.png" },
  craft_recovery_compass: { id: "craft_recovery_compass", title: "Recovery", desc: "Recovery compasses crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_recovery_compass.png" },
  craft_respawn_anchor: { id: "craft_respawn_anchor", title: "Respawn", desc: "Respawn Anchors crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_respawn_anchor.png" },
  craft_sponge: { id: "craft_sponge", title: "Spongebob", desc: "Sponges dried", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_sponge.png" },
  craft_spyglass: { id: "craft_spyglass", title: "Voyeur", desc: "Spyglasses crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_spyglass.png" },
  craft_sword: { id: "craft_sword", title: "Blacksmith", desc: "Swords crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_sword.png" },
  craft_tnt: { id: "craft_tnt", title: "Bad Intentions", desc: "TNT crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_tnt.png" },
  craft_tools: { id: "craft_tools", title: "Workshop", desc: "Tools crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_tools.png" },
  craft_turtle_helmet: { id: "craft_turtle_helmet", title: "Turtlehead", desc: "Turtle Helmets crafted", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_turtle_helmet.png" },
  craft_wool: { id: "craft_wool", title: "Carpet Dealer", desc: "Wool/carpets crafted/dyed", unit: "int", bucket: "crafting", icon: "/awards/icons/craft_wool.png" },
  crouch: { id: "crouch", title: "Sneaky", desc: "Distance crouched", unit: "cm", bucket: "movement", icon: "/awards/icons/crouch.png" },
  damage_dealt: { id: "damage_dealt", title: "Berserk!", desc: "Damage dealt", unit: "tenths_of_heart", bucket: "combat", icon: "/awards/icons/damage_dealt.png" },
  damage_shield: { id: "damage_shield", title: "Shield", desc: "Damage blocked", unit: "tenths_of_heart", bucket: "combat", icon: "/awards/icons/damage_shield.png" },
  damage_taken: { id: "damage_taken", title: "Ouch!", desc: "Damage taken", unit: "tenths_of_heart", bucket: "combat", icon: "/awards/icons/damage_taken.png" },
  death: { id: "death", title: "Lemming", desc: "Times died", unit: "int", bucket: "combat", icon: "/awards/icons/death.png" },
  dive: { id: "dive", title: "Diver", desc: "Distance dived", unit: "cm", bucket: "movement", icon: "/awards/icons/dive.png" },
  drink_milk: { id: "drink_milk", title: "Milksop", desc: "Milk buckets drunk", unit: "int", bucket: "items", icon: "/awards/icons/drink_milk.png" },
  drop: { id: "drop", title: "Dropper", desc: "Items dropped", unit: "int", bucket: "items", icon: "/awards/icons/drop.png" },
  eat_cookie: { id: "eat_cookie", title: "Cookie Monster", desc: "Cookies eaten", unit: "int", bucket: "food", icon: "/awards/icons/eat_cookie.png" },
  eat_fish: { id: "eat_fish", title: "Fish Gourmet", desc: "Fish eaten", unit: "int", bucket: "food", icon: "/awards/icons/eat_fish.png" },
  eat_junkfood: { id: "eat_junkfood", title: "Bad Diet", desc: "Junkfood items eaten", unit: "int", bucket: "food", icon: "/awards/icons/eat_junkfood.png" },
  eat_meat: { id: "eat_meat", title: "Carnivore", desc: "Meat items eaten", unit: "int", bucket: "food", icon: "/awards/icons/eat_meat.png" },
  eat_rawmeat: { id: "eat_rawmeat", title: "Raw Eater", desc: "Raw meat items eaten", unit: "int", bucket: "food", icon: "/awards/icons/eat_rawmeat.png" },
  eat_soup: { id: "eat_soup", title: "Soupy Caspar", desc: "Soups and stews eaten", unit: "int", bucket: "food", icon: "/awards/icons/eat_soup.png" },
  eat_veggie: { id: "eat_veggie", title: "Vegetarian", desc: "Veggie items eaten", unit: "int", bucket: "food", icon: "/awards/icons/eat_veggie.png" },
  enchant: { id: "enchant", title: "Enchanter", desc: "Items enchanted", unit: "int", bucket: "items", icon: "/awards/icons/enchant.png" },
  fall: { id: "fall", title: "Base Jumper", desc: "Distance fallen", unit: "cm", bucket: "movement", icon: "/awards/icons/fall.png" },
  harvest_bamboo: { id: "harvest_bamboo", title: "Bamboozled", desc: "Bamboo harvested", unit: "int", bucket: "food", icon: "/awards/icons/harvest_bamboo.png" },
  harvest_nether_wart: { id: "harvest_nether_wart", title: "Nether Farmer", desc: "Nether warts harvested", unit: "int", bucket: "food", icon: "/awards/icons/harvest_nether_wart.png" },
  harvest_sugar: { id: "harvest_sugar", title: "Sugar High", desc: "Sugar harvested", unit: "int", bucket: "food", icon: "/awards/icons/harvest_sugar.png" },
  interact_anvil: { id: "interact_anvil", title: "Smith", desc: "Anvil interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_anvil.png" },
  interact_blast_furnace: { id: "interact_blast_furnace", title: "Smelter", desc: "Blast Furnace interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_blast_furnace.png" },
  interact_brewing_stand: { id: "interact_brewing_stand", title: "Brewer", desc: "Brewing Stand interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_brewing_stand.png" },
  interact_campfire: { id: "interact_campfire", title: "Primitive Technology", desc: "Campfire interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_campfire.png" },
  interact_cartography: { id: "interact_cartography", title: "Cartographer", desc: "Cartography table interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_cartography.png" },
  interact_grindstone: { id: "interact_grindstone", title: "I Fix It", desc: "Grindstone interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_grindstone.png" },
  interact_lectern: { id: "interact_lectern", title: "Lector", desc: "Lectern interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_lectern.png" },
  interact_loom: { id: "interact_loom", title: "Tailor", desc: "Loom interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_loom.png" },
  interact_smoker: { id: "interact_smoker", title: "Chef", desc: "Smoker interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_smoker.png" },
  interact_stonecutter: { id: "interact_stonecutter", title: "Mason", desc: "Stonecutter interactions", unit: "int", bucket: "items", icon: "/awards/icons/interact_stonecutter.png" },
  jump: { id: "jump", title: "Bunnyhopper", desc: "Times jumped", unit: "int", bucket: "movement", icon: "/awards/icons/jump.png" },
  kill_allay: { id: "kill_allay", title: "No, Thanks", desc: "Allays killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_allay.png" },
  kill_any: { id: "kill_any", title: "Killing Spree!", desc: "Total mobs killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_any.png" },
  kill_axolotl: { id: "kill_axolotl", title: "Sir Axolot", desc: "Axolotls killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_axolotl.png" },
  kill_bat: { id: "kill_bat", title: "Bat Flap", desc: "Bats killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_bat.png" },
  kill_bee: { id: "kill_bee", title: "Beegone!", desc: "Bees killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_bee.png" },
  kill_blaze: { id: "kill_blaze", title: "Extinguisher", desc: "Blazes killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_blaze.png" },
  kill_camel: { id: "kill_camel", title: "Desert Deleter", desc: "Camels killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_camel.png" },
  kill_chicken: { id: "kill_chicken", title: "Chicken Griller", desc: "Chickens killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_chicken.png" },
  kill_cow: { id: "kill_cow", title: "Cow Tipper", desc: "Cows killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_cow.png" },
  kill_creeper: { id: "kill_creeper", title: "Creeper Creep", desc: "Creepers killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_creeper.png" },
  kill_dolphin: { id: "kill_dolphin", title: "Dolphin Hunter", desc: "Dolphins killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_dolphin.png" },
  kill_ender_dragon: { id: "kill_ender_dragon", title: "Dragon Hunter", desc: "Ender Dragons killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_ender_dragon.png" },
  kill_enderman: { id: "kill_enderman", title: "Enderman Ender", desc: "Endermen killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_enderman.png" },
  kill_endermite: { id: "kill_endermite", title: "End Ratter", desc: "Endermite killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_endermite.png" },
  kill_fish: { id: "kill_fish", title: "Fish Catcher", desc: "Fish killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_fish.png" },
  kill_fox: { id: "kill_fox", title: "What Does The Fox Say?", desc: "Foxes killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_fox.png" },
  kill_frog: { id: "kill_frog", title: "Ribbit Apart", desc: "Frogs Killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_frog.png" },
  kill_ghast: { id: "kill_ghast", title: "Tear Drinker", desc: "Ghasts killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_ghast.png" },
  kill_goat: { id: "kill_goat", title: "G.O.A.T.", desc: "Goats killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_goat.png" },
  kill_guardian: { id: "kill_guardian", title: "Underwater Raider", desc: "Score vs Guardians", unit: "int", bucket: "combat", icon: "/awards/icons/kill_guardian.png" },
  kill_hoglins: { id: "kill_hoglins", title: "Hakuna Matata", desc: "Hoglins & Zoglins killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_hoglins.png" },
  kill_horse: { id: "kill_horse", title: "Horse Hater", desc: "Horses killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_horse.png" },
  kill_illagers: { id: "kill_illagers", title: "Cleanser", desc: "Illagers killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_illagers.png" },
  kill_iron_golem: { id: "kill_iron_golem", title: "Traitor", desc: "Iron Golems killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_iron_golem.png" },
  kill_llama: { id: "kill_llama", title: "Caravan Bandit", desc: "LLamas killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_llama.png" },
  kill_magma_cube: { id: "kill_magma_cube", title: "Magma Cream", desc: "Magma Cubes killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_magma_cube.png" },
  kill_mooshroom: { id: "kill_mooshroom", title: "Mycelium Cowboy", desc: "Mooshrooms killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_mooshroom.png" },
  kill_ocelot: { id: "kill_ocelot", title: "Kitty Killer", desc: "Ocelots and Cats killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_ocelot.png" },
  kill_panda: { id: "kill_panda", title: "Kung FU! Panda", desc: "Pandas killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_panda.png" },
  kill_parrot: { id: "kill_parrot", title: "Stupid Bird!", desc: "Parrots killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_parrot.png" },
  kill_phantom: { id: "kill_phantom", title: "Phantom Shooter", desc: "Phantoms killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_phantom.png" },
  kill_pig: { id: "kill_pig", title: "Pork Chopper", desc: "Pigs killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_pig.png" },
  kill_piglin: { id: "kill_piglin", title: "Kill or Be Killed", desc: "Piglins killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_piglin.png" },
  kill_piglin_brute: { id: "kill_piglin_brute", title: "Brutal", desc: "Piglin Brutes killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_piglin_brute.png" },
  kill_polar_bear: { id: "kill_polar_bear", title: "Polar Hunter", desc: "Polar Bears killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_polar_bear.png" },
  kill_rabbit: { id: "kill_rabbit", title: "Bunny Killer :(", desc: "Rabbits killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_rabbit.png" },
  kill_ravager: { id: "kill_ravager", title: "Ravaging!", desc: "Ravagers killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_ravager.png" },
  kill_sheep: { id: "kill_sheep", title: "Big Bad Wolf", desc: "Sheep killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_sheep.png" },
  kill_shulker: { id: "kill_shulker", title: "Shulker Cracker", desc: "Shulkers killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_shulker.png" },
  kill_silverfish: { id: "kill_silverfish", title: "Nasty Little...", desc: "Silverfish killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_silverfish.png" },
  kill_skeleton: { id: "kill_skeleton", title: "Bone Collector", desc: "Skeletons/Strays killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_skeleton.png" },
  kill_slime: { id: "kill_slime", title: "Swamp Lurker", desc: "Slimes killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_slime.png" },
  kill_sniffer: { id: "kill_sniffer", title: "Sniffed Away", desc: "Sniffers killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_sniffer.png" },
  kill_snow_golem: { id: "kill_snow_golem", title: "AntiFrosty", desc: "Snow Golems killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_snow_golem.png" },
  kill_spider: { id: "kill_spider", title: "Arachnophobia", desc: "Spiders killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_spider.png" },
  kill_squid: { id: "kill_squid", title: "Pool Cleaner", desc: "Squids killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_squid.png" },
  kill_strider: { id: "kill_strider", title: "Lava Pool Cleaner", desc: "Striders killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_strider.png" },
  kill_tadpole: { id: "kill_tadpole", title: "Obliterator", desc: "Tadpoles Killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_tadpole.png" },
  kill_turtle: { id: "kill_turtle", title: "Super Mario", desc: "Turtles killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_turtle.png" },
  kill_vex: { id: "kill_vex", title: "Vex Hunter", desc: "Vexes killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_vex.png" },
  kill_villager: { id: "kill_villager", title: "Bully", desc: "Villagers killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_villager.png" },
  kill_wandering_trader: { id: "kill_wandering_trader", title: "Trade Sanctions", desc: "Wandering Traders killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_wandering_trader.png" },
  kill_warden: { id: "kill_warden", title: "You Can't See Me", desc: "Wardens killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_warden.png" },
  kill_witch: { id: "kill_witch", title: "Witch Hunter", desc: "Witches killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_witch.png" },
  kill_wither_skeleton: { id: "kill_wither_skeleton", title: "Wither Or Not", desc: "Wither Skeletons killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_wither_skeleton.png" },
  kill_wolf: { id: "kill_wolf", title: "Bad Dog!", desc: "Wolves and Dogs killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_wolf.png" },
  kill_zombie: { id: "kill_zombie", title: "Zombie Grinder", desc: "Zombies/Husks/Drowned killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_zombie.png" },
  kill_zombified_piglin: { id: "kill_zombified_piglin", title: "Nether Gang War", desc: "Zombified Piglins killed", unit: "int", bucket: "combat", icon: "/awards/icons/kill_zombified_piglin.png" },
  killed_by_creeper: { id: "killed_by_creeper", title: "Keboom!", desc: "Times Killed by Creepers", unit: "int", bucket: "combat", icon: "/awards/icons/killed_by_creeper.png" },
  killed_by_warden: { id: "killed_by_warden", title: "Stay out!", desc: "Times Killed by Wardens", unit: "int", bucket: "combat", icon: "/awards/icons/killed_by_warden.png" },
  mine_amethyst: { id: "mine_amethyst", title: "Jeweler", desc: "Amethysts mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_amethyst.png" },
  mine_ancient_debris: { id: "mine_ancient_debris", title: "Archeologist", desc: "Ancient Debris mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_ancient_debris.png" },
  mine_coal_ore: { id: "mine_coal_ore", title: "Black Gold", desc: "Coal Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_coal_ore.png" },
  mine_cobweb: { id: "mine_cobweb", title: "Silky Situation", desc: "Cobweb removed", unit: "int", bucket: "mining", icon: "/awards/icons/mine_cobweb.png" },
  mine_copper_ore: { id: "mine_copper_ore", title: "Copper Miner", desc: "Copper Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_copper_ore.png" },
  mine_coral: { id: "mine_coral", title: "Coral Collector", desc: "Corals mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_coral.png" },
  mine_diamond_ore: { id: "mine_diamond_ore", title: "Diamonds!", desc: "Diamond Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_diamond_ore.png" },
  mine_dimensional: { id: "mine_dimensional", title: "Terraformer", desc: "Netherrack/End stone mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_dimensional.png" },
  mine_emerald_ore: { id: "mine_emerald_ore", title: "Mountain Miner", desc: "Emerald Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_emerald_ore.png" },
  mine_glass: { id: "mine_glass", title: "Glassbreaker", desc: "Glass broken", unit: "int", bucket: "mining", icon: "/awards/icons/mine_glass.png" },
  mine_gold_ore: { id: "mine_gold_ore", title: "Gold Rush", desc: "Gold Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_gold_ore.png" },
  mine_grass: { id: "mine_grass", title: "Lawnmower", desc: "Grass removed", unit: "int", bucket: "mining", icon: "/awards/icons/mine_grass.png" },
  mine_ground: { id: "mine_ground", title: "Excavator", desc: "Dirt, sand etc. mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_ground.png" },
  mine_ice: { id: "mine_ice", title: "Ice Breaker", desc: "Ice broken", unit: "int", bucket: "mining", icon: "/awards/icons/mine_ice.png" },
  mine_iron_ore: { id: "mine_iron_ore", title: "Iron Heart", desc: "Iron Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_iron_ore.png" },
  mine_kelp: { id: "mine_kelp", title: "I Need Kelp!", desc: "Kelp mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_kelp.png" },
  mine_lapis_ore: { id: "mine_lapis_ore", title: "Blue", desc: "Lapis Lazuli Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_lapis_ore.png" },
  mine_nether_foliage: { id: "mine_nether_foliage", title: "Nether Mower", desc: "Nether sprouts & roots removed", unit: "int", bucket: "mining", icon: "/awards/icons/mine_nether_foliage.png" },
  mine_nether_quartz_ore: { id: "mine_nether_quartz_ore", title: "Quartz", desc: "Nether Quartz Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_nether_quartz_ore.png" },
  mine_obsidian: { id: "mine_obsidian", title: "Obsidian Miner", desc: "Obsidian blocks mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_obsidian.png" },
  mine_pointed_dripstone: { id: "mine_pointed_dripstone", title: "Cave Dweller", desc: "Pointed Dripstone mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_pointed_dripstone.png" },
  mine_redstone_ore: { id: "mine_redstone_ore", title: "Redstone Miner", desc: "Redstone Ore mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_redstone_ore.png" },
  mine_snow: { id: "mine_snow", title: "Snow Pusher", desc: "Snow removed", unit: "int", bucket: "mining", icon: "/awards/icons/mine_snow.png" },
  mine_spawner: { id: "mine_spawner", title: "Nope!", desc: "Spawners removed", unit: "int", bucket: "mining", icon: "/awards/icons/mine_spawner.png" },
  mine_stone: { id: "mine_stone", title: "Stonemason", desc: "Stone mined", unit: "int", bucket: "mining", icon: "/awards/icons/mine_stone.png" },
  mine_wood: { id: "mine_wood", title: "Woodcutter", desc: "Wood blocks cut", unit: "int", bucket: "mining", icon: "/awards/icons/mine_wood.png" },
  noteblock: { id: "noteblock", title: "Musician", desc: "Note block interactions", unit: "int", bucket: "items", icon: "/awards/icons/noteblock.png" },
  open_container: { id: "open_container", title: "Warehouse", desc: "Containers opened", unit: "int", bucket: "items", icon: "/awards/icons/open_container.png" },
  place_banner: { id: "place_banner", title: "Flying Flags", desc: "Banners placed", unit: "int", bucket: "building", icon: "/awards/icons/place_banner.png" },
  place_bars: { id: "place_bars", title: "Jailer", desc: "Iron bars & chains placed", unit: "int", bucket: "building", icon: "/awards/icons/place_bars.png" },
  place_cactus: { id: "place_cactus", title: "Cactus Farmer", desc: "Cacti planted", unit: "int", bucket: "building", icon: "/awards/icons/place_cactus.png" },
  place_candle: { id: "place_candle", title: "Candlelight Dinner", desc: "Candles placed", unit: "int", bucket: "building", icon: "/awards/icons/place_candle.png" },
  place_chorus_flower: { id: "place_chorus_flower", title: "Chorus Farmer", desc: "Chorus Flowers planted", unit: "int", bucket: "building", icon: "/awards/icons/place_chorus_flower.png" },
  place_conveyor: { id: "place_conveyor", title: "Conveyor", desc: "Hoppers and droppers placed", unit: "int", bucket: "building", icon: "/awards/icons/place_conveyor.png" },
  place_electrics: { id: "place_electrics", title: "Electrician", desc: "Redstone items placed", unit: "int", bucket: "building", icon: "/awards/icons/place_electrics.png" },
  place_glass: { id: "place_glass", title: "Glassworker", desc: "Glass placed", unit: "int", bucket: "building", icon: "/awards/icons/place_glass.png" },
  place_lantern: { id: "place_lantern", title: "Fear Of The Dark", desc: "Lanterns placed", unit: "int", bucket: "building", icon: "/awards/icons/place_lantern.png" },
  place_lightning_rod: { id: "place_lightning_rod", title: "Benjamin Franklin", desc: "Lightning Rods placed", unit: "int", bucket: "building", icon: "/awards/icons/place_lightning_rod.png" },
  place_lodestone: { id: "place_lodestone", title: "Lodecrumb Trail", desc: "Lodestone placed", unit: "int", bucket: "building", icon: "/awards/icons/place_lodestone.png" },
  place_piston: { id: "place_piston", title: "Mechanic", desc: "Pistons placed", unit: "int", bucket: "building", icon: "/awards/icons/place_piston.png" },
  place_rails: { id: "place_rails", title: "Railway Company", desc: "Rails placed", unit: "int", bucket: "building", icon: "/awards/icons/place_rails.png" },
  place_sapling: { id: "place_sapling", title: "Forester", desc: "Trees planted", unit: "int", bucket: "building", icon: "/awards/icons/place_sapling.png" },
  place_scaffolding: { id: "place_scaffolding", title: "Bob The Builder", desc: "Scaffoldings placed", unit: "int", bucket: "building", icon: "/awards/icons/place_scaffolding.png" },
  place_sign: { id: "place_sign", title: "README.TXT", desc: "Signs placed", unit: "int", bucket: "building", icon: "/awards/icons/place_sign.png" },
  place_stairs: { id: "place_stairs", title: "MaStair", desc: "Stairs built", unit: "int", bucket: "building", icon: "/awards/icons/place_stairs.png" },
  place_torch: { id: "place_torch", title: "Enlightened", desc: "Torches placed", unit: "int", bucket: "building", icon: "/awards/icons/place_torch.png" },
  place_wall: { id: "place_wall", title: "Iron Curtain", desc: "Walls placed", unit: "int", bucket: "building", icon: "/awards/icons/place_wall.png" },
  play: { id: "play", title: "Dedication", desc: "Total time played", unit: "ticks", bucket: "misc", icon: "/awards/icons/play.png" },
  play_record: { id: "play_record", title: "Disc Jockey", desc: "Records played", unit: "int", bucket: "items", icon: "/awards/icons/play_record.png" },
  pot_flower: { id: "pot_flower", title: "Florist", desc: "Flowers potted", unit: "int", bucket: "items", icon: "/awards/icons/pot_flower.png" },
  ride_boat: { id: "ride_boat", title: "Sailor", desc: "Distance gone by boat", unit: "cm", bucket: "movement", icon: "/awards/icons/ride_boat.png" },
  ride_horse: { id: "ride_horse", title: "Rider", desc: "Distance ridden on a horse", unit: "cm", bucket: "movement", icon: "/awards/icons/ride_horse.png" },
  ride_minecart: { id: "ride_minecart", title: "Public Transport", desc: "Distance gone in a minecart", unit: "cm", bucket: "movement", icon: "/awards/icons/ride_minecart.png" },
  ride_pig: { id: "ride_pig", title: "Because I Can!", desc: "Distance ridden on a pig", unit: "cm", bucket: "movement", icon: "/awards/icons/ride_pig.png" },
  ride_strider: { id: "ride_strider", title: "The Floor Is Lava", desc: "Distance ridden on a strider", unit: "cm", bucket: "movement", icon: "/awards/icons/ride_strider.png" },
  ring_bell: { id: "ring_bell", title: "Ding Dong Ditch!", desc: "Bells rung", unit: "int", bucket: "items", icon: "/awards/icons/ring_bell.png" },
  sleep: { id: "sleep", title: "Sleepyhead", desc: "Times slept", unit: "int", bucket: "misc", icon: "/awards/icons/sleep.png" },
  sprint: { id: "sprint", title: "Marathon", desc: "Distance sprinted", unit: "cm", bucket: "movement", icon: "/awards/icons/sprint.png" },
  swim: { id: "swim", title: "Swimmer", desc: "Distance swum", unit: "cm", bucket: "movement", icon: "/awards/icons/swim.png" },
  time_since_death: { id: "time_since_death", title: "Survivor", desc: "Time since last death", unit: "ticks", bucket: "misc", icon: "/awards/icons/time_since_death.png" },
  time_since_sleep: { id: "time_since_sleep", title: "Insomnia", desc: "Time since last sleep", unit: "ticks", bucket: "misc", icon: "/awards/icons/time_since_sleep.png" },
  trade: { id: "trade", title: "Trader", desc: "Villager trades", unit: "int", bucket: "misc", icon: "/awards/icons/trade.png" },
  trigger_raid: { id: "trigger_raid", title: "Bad Omen", desc: "Raids triggered", unit: "int", bucket: "misc", icon: "/awards/icons/trigger_raid.png" },
  use_book: { id: "use_book", title: "Bestseller", desc: "Books written", unit: "int", bucket: "items", icon: "/awards/icons/use_book.png" },
  use_bow: { id: "use_bow", title: "Archer", desc: "Arrows shot", unit: "int", bucket: "items", icon: "/awards/icons/use_bow.png" },
  use_crossbow: { id: "use_crossbow", title: "Sharpshooter", desc: "Bolts fired", unit: "int", bucket: "items", icon: "/awards/icons/use_crossbow.png" },
  use_dirt: { id: "use_dirt", title: "Getting Dirty", desc: "Dirt blocks placed", unit: "int", bucket: "items", icon: "/awards/icons/use_dirt.png" },
  use_egg: { id: "use_egg", title: "Catch!", desc: "Eggs thrown", unit: "int", bucket: "items", icon: "/awards/icons/use_egg.png" },
  use_ender_eye: { id: "use_ender_eye", title: "Stronghold Seeker", desc: "Ender eyes thrown", unit: "int", bucket: "items", icon: "/awards/icons/use_ender_eye.png" },
  use_ender_pearl: { id: "use_ender_pearl", title: "Translocator", desc: "Ender pearls thrown", unit: "int", bucket: "items", icon: "/awards/icons/use_ender_pearl.png" },
  use_fireworks: { id: "use_fireworks", title: "Happy New Year!", desc: "Fireworks started", unit: "int", bucket: "items", icon: "/awards/icons/use_fireworks.png" },
  use_flint: { id: "use_flint", title: "Pyromaniac", desc: "Fires started", unit: "int", bucket: "items", icon: "/awards/icons/use_flint.png" },
  use_goat_horn: { id: "use_goat_horn", title: "Sound the Charge!", desc: "Goat horns sounded", unit: "int", bucket: "items", icon: "/awards/icons/use_goat_horn.png" },
  use_hoe: { id: "use_hoe", title: "Farmer", desc: "Ground blocks plowed", unit: "int", bucket: "items", icon: "/awards/icons/use_hoe.png" },
  use_honey_bottle: { id: "use_honey_bottle", title: "Winnie the Pooh", desc: "Honey bottles drunk", unit: "int", bucket: "items", icon: "/awards/icons/use_honey_bottle.png" },
  use_lava_bucket: { id: "use_lava_bucket", title: "Napalm", desc: "Lava buckets emptied", unit: "int", bucket: "items", icon: "/awards/icons/use_lava_bucket.png" },
  use_potion: { id: "use_potion", title: "Alchemist", desc: "Potions used", unit: "int", bucket: "items", icon: "/awards/icons/use_potion.png" },
  use_shears: { id: "use_shears", title: "Cutter", desc: "Shear uses", unit: "int", bucket: "items", icon: "/awards/icons/use_shears.png" },
  use_snowball: { id: "use_snowball", title: "Snowball Fight!", desc: "Snowballs thrown", unit: "int", bucket: "items", icon: "/awards/icons/use_snowball.png" },
  use_totem: { id: "use_totem", title: "Nine Lives", desc: "Totems of Undying used", unit: "int", bucket: "items", icon: "/awards/icons/use_totem.png" },
  use_water_bucket: { id: "use_water_bucket", title: "Aqueduct", desc: "Water buckets emptied", unit: "int", bucket: "items", icon: "/awards/icons/use_water_bucket.png" },
  walk: { id: "walk", title: "Traveler", desc: "Distance walked", unit: "cm", bucket: "movement", icon: "/awards/icons/walk.png" },
  walk_on_water: { id: "walk_on_water", title: "Water Walker", desc: "Distance walked on water", unit: "cm", bucket: "movement", icon: "/awards/icons/walk_on_water.png" },
  win_raid: { id: "win_raid", title: "Hero", desc: "Raids won", unit: "int", bucket: "misc", icon: "/awards/icons/win_raid.png" },
};

export const AWARD_IDS: readonly string[] = Object.freeze(Object.keys(AWARDS));

export function getAward(id: string): AwardMeta | null {
  return Object.prototype.hasOwnProperty.call(AWARDS, id) ? AWARDS[id] : null;
}

export const AWARD_BUCKET_LABELS: Record<AwardBucket, string> = {
  combat: "Combat",
  mining: "Mining",
  crafting: "Crafting",
  building: "Building",
  items: "Items",
  food: "Food",
  movement: "Movement",
  misc: "Misc",
};
