import type { BlockHuntClue, BlockHuntPuzzle } from "@/lib/blockHunt";

type MobHuntPuzzle = Omit<BlockHuntPuzzle, "texture">;

const clueKinds: readonly BlockHuntClue["kind"][] = [
  "data",
  "shape",
  "world",
  "behaviour",
  "behaviour",
  "world",
];

const clueLabels = [
  "Disposition",
  "General behaviour",
  "Spawning",
  "Behaviour",
  "Distinctive trait",
  "Identity",
] as const;

function mobPuzzle(
  answer: string,
  clues: readonly [string, string, string, string, string, string],
): MobHuntPuzzle {
  return {
    answer,
    clues: clues.map((text, index) => ({
      kind: clueKinds[index],
      label: clueLabels[index],
      text,
    })),
  };
}

// Facts are curated from the corresponding current Java Edition pages on Minecraft Wiki.
export const MOB_HUNT_PUZZLES: readonly MobHuntPuzzle[] = [
  mobPuzzle("Guardian", [
    "This mob is classified as hostile.",
    "Its combat includes a ranged attack.",
    "It spawns in and around ocean monuments when water and local conditions are suitable.",
    "It locks onto a target before releasing a beam whose damage cannot be avoided by simply moving sideways.",
    "When stranded on land it flops towards water rather than immediately suffocating.",
    "This spiky monument defender attacks with a charged laser beam.",
  ]),
  mobPuzzle("Allay", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "It appears in cages beside pillager outposts and in jail cells inside woodland mansions.",
    "After receiving an item, it collects matching dropped items within its search range.",
    "A nearby playing jukebox makes it dance, allowing duplication with an amethyst shard.",
    "This small blue helper delivers collected items to a player or note block.",
  ]),
  mobPuzzle("Axolotl", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "It spawns underwater in lush caves when clay is below the spawning position.",
    "It attacks many aquatic mobs but normally ignores players, turtles, dolphins, and frogs.",
    "After helping it defeat a target, a player can receive Regeneration and have Mining Fatigue removed.",
    "This bucketable cave amphibian sometimes plays dead when injured.",
  ]),
  mobPuzzle("Bee", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "Natural nests generate with these occupants near certain oak, birch, and cherry trees.",
    "It gathers pollen from flowers, fertilises crops, and increases the honey level when it returns home.",
    "After stinging, it loses its stinger and dies roughly one minute later.",
    "This striped pollinator lives in nests and produces honey.",
  ]),
  mobPuzzle("Blaze", [
    "This mob is classified as hostile.",
    "This mob can spawn naturally in the Nether.",
    "Nether fortresses contain both natural spawning areas and dedicated spawners for it.",
    "It rises before firing a burst of three flaming projectiles, then pauses before attacking again.",
    "Its rods are the survival source of blaze powder, making it essential for brewing and reaching the End.",
    "This yellow Nether fortress mob attacks with fireballs.",
  ]),
  mobPuzzle("Bogged", [
    "This mob is classified as hostile.",
    "Its combat includes a ranged attack.",
    "It spawns in swamps and mangrove swamps and can appear from certain trial spawners.",
    "Its bow attack is slower than a skeleton's but applies Poison for four seconds.",
    "Killing it can produce a tipped arrow of Poison in addition to ordinary skeleton drops.",
    "This green skeleton variant fires poisoned arrows from swampy habitats.",
  ]),
  mobPuzzle("Breeze", [
    "This mob is classified as hostile.",
    "Its combat includes a ranged attack.",
    "Specific trial spawners in trial chambers summon it during combat challenges.",
    "It circles targets by leaping, then fires projectiles whose bursts cause powerful knockback.",
    "Its wind bursts operate buttons, levers, doors, trapdoors, bells, and several other components.",
    "This purple trial chamber mob drops breeze rods and controls the wind.",
  ]),
  mobPuzzle("Creaking", [
    "This mob is classified as hostile.",
    "Its combat relies mainly on close-range attacks.",
    "An active creaking heart between aligned pale oak logs creates one at night.",
    "It moves only when no survival or adventure player is looking directly at it.",
    "Damage makes particles trace back to its heart, which must be destroyed to remove the protected mob.",
    "This wooden Pale Garden creature freezes under a player's gaze.",
  ]),
  mobPuzzle("Creeper", [
    "This mob is classified as hostile.",
    "Its combat relies mainly on close-range attacks.",
    "It spawns in the Overworld at light level zero, except in mushroom fields and the deep dark.",
    "It approaches silently, begins a short fuse near a player, and abandons the explosion if the target escapes.",
    "Lightning charges it, greatly increasing blast power and enabling several mob head drops.",
    "This iconic green monster hisses immediately before exploding.",
  ]),
  mobPuzzle("Enderman", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Its combat relies mainly on close-range attacks.",
    "It spawns in all three dimensions, but is especially common in warped forests and the End.",
    "Direct eye contact provokes it, while wearing a carved pumpkin prevents that visual trigger.",
    "It can pick up and relocate a restricted set of blocks when mob griefing is enabled.",
    "This tall dark mob teleports and commonly drops ender pearls.",
  ]),
  mobPuzzle("Evoker", [
    "This mob is classified as hostile.",
    "Its combat includes a ranged attack.",
    "It naturally appears in woodland mansions and in later waves of village raids.",
    "One spell raises a line of damaging fangs, while another summons flying attackers.",
    "It is the only renewable source of the item that prevents death when held.",
    "This robed illager summons vexes and always drops a totem of undying.",
  ]),
  mobPuzzle("Frog", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "Tadpoles mature into a variant chosen by the temperature of the biome where they grow up.",
    "It attacks small slimes and magma cubes by extending its tongue.",
    "Eating the smallest magma cube creates a froglight whose colour depends on the variant.",
    "This amphibian grows from a tadpole and is bred using slimeballs.",
  ]),
  mobPuzzle("Happy Ghast", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "A dried form must first be hydrated into a ghastling, then fed or allowed to mature.",
    "It follows tempting snowballs and can be tethered to blocks using leads.",
    "A harness turns the top of its body into a rideable platform controlled by the front passenger.",
    "This smiling Overworld-friendly ghast variant begins life as a dried block from the Nether.",
  ]),
  mobPuzzle("Iron Golem", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "Villages can summon it when villagers meet social and population conditions, or players can build one from blocks.",
    "It patrols villages and launches many hostile mobs into the air with heavy upward swings.",
    "Damage exposes progressive cracks that can be repaired by using iron ingots on it.",
    "This large village defender can be built from four iron blocks and a carved pumpkin.",
  ]),
  mobPuzzle("Phantom", [
    "This mob is classified as hostile.",
    "Its combat relies mainly on close-range attacks.",
    "It can spawn at night above players who have avoided sleep for at least three in-game days.",
    "It circles high overhead before swooping down to strike its target.",
    "Cats hiss at it, and its membrane drop repairs elytra or brews Slow Falling potions.",
    "This nocturnal blue flyer punishes players who have not slept.",
  ]),
  mobPuzzle("Shulker", [
    "This mob is classified as hostile.",
    "Its combat includes a ranged attack.",
    "It naturally generates attached to solid surfaces throughout End cities.",
    "Its homing projectile follows grid-aligned paths and applies Levitation on impact.",
    "When hit by another of its projectiles, it can teleport and sometimes create another member of its kind.",
    "This purple box-shaped End mob drops shells used for portable storage.",
  ]),
  mobPuzzle("Sniffer", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "It does not spawn naturally; two eggs found through archaeology are needed to establish a renewable population.",
    "Adults periodically smell the ground, search for a valid spot, and dig up ancient seeds.",
    "It remembers recently used digging positions and refuses to search those same locations again for a time.",
    "This huge ancient mob hatches from an egg and uncovers torchflower seeds and pitcher pods.",
  ]),
  mobPuzzle("Strider", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "This mob can spawn naturally in the Nether.",
    "It spawns on lava, with some appearing beneath a riding zombified piglin.",
    "It walks freely across lava but moves much more slowly on land and takes damage from water and rain.",
    "A saddle and warped fungus on a stick let a player control it across lava oceans.",
    "This red Nether mount is the survival transport designed for lava.",
  ]),
  mobPuzzle("Warden", [
    "This mob is classified as hostile.",
    "Its combat includes a ranged attack.",
    "Repeated activation of naturally generated sculk shriekers can summon it from the deep dark floor.",
    "It is blind, building anger by detecting vibrations, smelling nearby entities, or being touched.",
    "Its sonic boom passes through blocks and ignores armour, shields, and protection enchantments.",
    "This ancient city threat is meant to be avoided rather than fought.",
  ]),
  mobPuzzle("Wither", [
    "This mob is classified as hostile.",
    "Players can reproduce or create this mob without commands.",
    "Players summon it by arranging soul sand or soul soil with three wither skeleton skulls.",
    "After charging its health, it creates a large initial explosion and begins firing explosive skulls.",
    "At half health it becomes immune to arrows, and its death always produces a nether star.",
    "This player-built three-headed boss inflicts the Wither effect.",
  ]),
  mobPuzzle("Piglin", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "This mob can spawn naturally in the Nether.",
    "It spawns in Nether wastes, crimson forests, and bastion remnants.",
    "Wearing at least one piece of gold armour prevents its normal hostility, but opening guarded containers still provokes it.",
    "Giving an adult a gold ingot starts bartering and returns one selection from a special loot table.",
    "This gold-loving Nether humanoid becomes zombified outside its home dimension.",
  ]),
  mobPuzzle("Armadillo", [
    "This mob is classified as passive, neutral, or utility rather than hostile.",
    "Players can reproduce or create this mob without commands.",
    "It spawns in savanna and badlands biomes, including several warmer variants.",
    "Nearby sprinting players, undead mobs, or hostile riders can make it roll into a defensive ball.",
    "It periodically sheds scutes, and brushing it produces extra scutes at a durability cost.",
    "This small savanna animal supplies the material used to craft wolf armour.",
  ]),
];
