pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'papermc'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'CrabUtilities'

include 'spigot'
include 'velocity'
include 'bingo-test'
